# Database Connect
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${TODO_POSTGRESQL_HOST}:${TODO_POSTGRESQL_PORT}/${TODO_DATA_BASE_NAME}
spring.datasource.username=${TODO_POSTGRESQL_USER_NAME}
spring.datasource.password=${TODO_POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Mapper xml location
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml

# AES Secret Key
aes.secret.key=58392058392058392058392058392058

# front_end url
front_end_url=${FRONT_END_URL}

# dev server
dev_server=${DEV_SERVER}
